name: Esegui test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  generate-coverage:
    runs-on: ubuntu-latest
    name: genera e carica Code Coverage in Report

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests 
        run: npm run test:coverage
       

      - name: Carico coverage 
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
